import {
  Customer,
  FamilyMember,
  CustomerDocument,
  BaseService,
  SubService,
  ServiceVisit,
  Transaction,
  Reminder,
  PendingWork,
  PendingWorkSummary,
  DashboardData,
  EmployeeUser,
  Application,
  AuditLog,
  Village,
  FamilyTreeNodeData,
  GovDocumentItem,
  AttendanceRecord,
  LeaveRecord,
  HolidayItem,
  LeaveBalance,
} from '@/types';
import { INITIAL_45_SERVICES } from './catalogData';

export const MOCK_DASHBOARD: DashboardData = {
  today_summary: {
    total_customers: 2,
    total_service_entries: 3,
    open_pending_work: 3,
    ready_for_delivery: 0,
    pending_reminders: 0,
  },
  business_summary: {
    total_billing: 450.0,
    advance_received: 0.0,
    outstanding_balance: 0.0,
    completed_services: 0,
    delivered_services: 0,
  },
  customer_summary: {
    active_members: 2,
    vip_members: 0,
    repeat_customers: 0,
    urgent_tasks: 0,
    documents_pending: 3,
  },
};

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 3,
    family_id: 'HTF-000002',
    registration_date: '2026-08-26',
    head_of_family: 'Dineshbhai Changani',
    mobile_number: '8000231125',
    whatsapp_number: '6354456881',
    family_member_count: 6,
    village_city: 'Bota',
    birth_date: '1974-04-12',
    referral_family_id: 'HTF-000001',
    document_consent: true,
    current_points: 20,
    wallet_balance: '0.00',
    total_visits: 1,
    last_visit: '2026-08-26',
    is_active: true,
    notes: 'Primary Bota family registration with full digital vault',
    digital_card_sent: true,
    created_at: '2026-08-26T04:11:31.469894Z',
    updated_at: '2026-08-26T07:37:44.143084Z',
  },
  {
    id: 1,
    family_id: 'HTF-000001',
    registration_date: '2026-08-25',
    head_of_family: 'Vitthalbhai Changani',
    mobile_number: '6789012345',
    whatsapp_number: '8000231124',
    family_member_count: 5,
    village_city: 'Bota',
    birth_date: '1985-05-23',
    referral_family_id: 'HTF-000002',
    document_consent: true,
    current_points: 20,
    wallet_balance: '0.00',
    total_visits: 1,
    last_visit: '2026-08-26',
    is_active: true,
    notes: 'Registration with family consent',
    digital_card_sent: false,
    created_at: '2026-08-25T04:52:43.520756Z',
    updated_at: '2026-08-26T07:37:44.146036Z',
  },
  {
    id: 4,
    family_id: 'HTF-000003',
    registration_date: '2026-08-28',
    head_of_family: 'Rameshbhai Patel',
    mobile_number: '9825123450',
    whatsapp_number: '9825123450',
    family_member_count: 4,
    village_city: 'Gunjar',
    birth_date: '1979-11-15',
    referral_family_id: 'HTF-000002',
    document_consent: true,
    current_points: 15,
    wallet_balance: '0.00',
    total_visits: 2,
    last_visit: '2026-09-01',
    is_active: true,
    notes: 'Gunjar agricultural household',
    digital_card_sent: true,
    created_at: '2026-08-28T09:15:00.000000Z',
    updated_at: '2026-09-01T11:20:00.000000Z',
  },
  {
    id: 5,
    family_id: 'HTF-000004',
    registration_date: '2026-08-29',
    head_of_family: 'Bharatbhai Changani',
    mobile_number: '9879011223',
    whatsapp_number: '9879011223',
    family_member_count: 5,
    village_city: 'Varna',
    birth_date: '1982-08-20',
    referral_family_id: 'HTF-000001',
    document_consent: true,
    current_points: 10,
    wallet_balance: '0.00',
    total_visits: 1,
    last_visit: '2026-08-29',
    is_active: true,
    notes: 'Varna village resident',
    digital_card_sent: true,
    created_at: '2026-08-29T10:00:00.000000Z',
    updated_at: '2026-08-29T10:00:00.000000Z',
  },
  {
    id: 6,
    family_id: 'HTF-000005',
    registration_date: '2026-08-30',
    head_of_family: 'Mansukhbhai Shah',
    mobile_number: '9898033445',
    whatsapp_number: '9898033445',
    family_member_count: 4,
    village_city: 'Gadhada',
    birth_date: '1976-03-10',
    referral_family_id: 'HTF-000002',
    document_consent: true,
    current_points: 25,
    wallet_balance: '0.00',
    total_visits: 3,
    last_visit: '2026-09-03',
    is_active: true,
    notes: 'Gadhada merchant family',
    digital_card_sent: true,
    created_at: '2026-08-30T12:00:00.000000Z',
    updated_at: '2026-09-03T14:30:00.000000Z',
  },
  {
    id: 7,
    family_id: 'HTF-000006',
    registration_date: '2026-09-02',
    head_of_family: 'Sanjaybhai Rathod',
    mobile_number: '9712044556',
    whatsapp_number: '9712044556',
    family_member_count: 5,
    village_city: 'Ranpur',
    birth_date: '1984-06-18',
    referral_family_id: 'HTF-000003',
    document_consent: true,
    current_points: 10,
    wallet_balance: '0.00',
    total_visits: 1,
    last_visit: '2026-09-02',
    is_active: true,
    notes: 'Ranpur township household',
    digital_card_sent: false,
    created_at: '2026-09-02T15:00:00.000000Z',
    updated_at: '2026-09-02T15:00:00.000000Z',
  },
];

export const MOCK_FAMILY_MEMBERS: Record<string, FamilyMember[]> = {
  'HTF-000002': [
    {
      id: 3,
      family_id: 'HTF-000002',
      name: 'Mitali Changani',
      relationship: 'DAUGHTER',
      mobile_number: '6354456888',
      birth_date: '2006-05-23',
      is_active: true,
      created_at: '2026-08-26T04:47:08.661368Z',
      customer: 3,
    },
    {
      id: 4,
      family_id: 'HTF-000002',
      name: 'Rekhaben Changani',
      relationship: 'WIFE',
      mobile_number: '8000231125',
      birth_date: '1989-03-12',
      is_active: true,
      created_at: '2026-08-26T05:12:00.000000Z',
      customer: 3,
    },
  ],
  'HTF-000001': [
    {
      id: 1,
      family_id: 'HTF-000001',
      name: 'Vitthalbhai Changani',
      relationship: 'HEAD',
      mobile_number: '6789012345',
      birth_date: '1985-05-23',
      is_active: true,
      created_at: '2026-08-25T04:55:00.000000Z',
      customer: 1,
    },
  ],
};

export const MOCK_DOCUMENTS: Record<string, CustomerDocument[]> = {
  'HTF-000002_3': [
    {
      id: 5,
      family_id: 'HTF-000002',
      member_name: 'Mitali Changani',
      document_type: 'AADHAR',
      document_type_display: 'Aadhar Card',
      document_name: 'Mitali Aadharcard',
      document_file: '/media/customer_documents/2026/08/aadharcard_old_t35FaHi.pdf',
      description: "Mitali's Aadharcard pdf",
      is_verified: true,
      created_at: '2026-08-27T06:36:14.119308Z',
      family_member: 3,
    },
  ],
};

export const MOCK_SERVICES: BaseService[] = [
  {
    id: 3,
    ServiceName: 'Aadhar Card',
    Description: 'Person must be present and all documents must be original',
    IsActive: true,
    CreatedAt: '2026-08-26T06:24:07.031182Z',
    UpdatedAt: '2026-08-26T06:37:03.318182Z',
    SubServices: [
      {
        id: 3,
        Service: 3,
        SubServiceName: 'New Aadhaar Card',
        Description: null,
        IsActive: true,
        CreatedAt: '2026-08-26T06:32:57.069323Z',
        UpdatedAt: '2026-08-26T06:32:57.069323Z',
        RequiredDocuments: [
          {
            id: 6,
            SubService: 3,
            document_type: 'BIRTH_CERTIFICATE',
            DocumentName: 'Child Birth Certificate with new QR and with full name',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:43:54.314136Z',
          },
          {
            id: 7,
            SubService: 3,
            document_type: 'AADHAR',
            DocumentName: 'Mother/Father Aadhaar Card',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:43:54.327136Z',
          },
        ],
      },
      {
        id: 4,
        Service: 3,
        SubServiceName: 'Change name for 5 - 12 years old person',
        Description: null,
        IsActive: true,
        CreatedAt: '2026-08-26T06:33:56.852726Z',
        UpdatedAt: '2026-08-26T06:33:56.852726Z',
        RequiredDocuments: [
          {
            id: 8,
            SubService: 4,
            document_type: 'BIRTH_CERTIFICATE',
            DocumentName: 'Birth Certificate',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:44:33.627388Z',
          },
          {
            id: 9,
            SubService: 4,
            document_type: 'AADHAR',
            DocumentName: 'Mother/Father Aadhaar Card',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:44:33.637388Z',
          },
        ],
      },
      {
        id: 5,
        Service: 3,
        SubServiceName: 'Change name for older than 12 years person',
        Description: null,
        IsActive: true,
        CreatedAt: '2026-08-26T06:34:30.735548Z',
        UpdatedAt: '2026-08-26T06:34:30.735548Z',
        RequiredDocuments: [
          {
            id: 10,
            SubService: 5,
            document_type: 'CASTE_CERTIFICATE',
            DocumentName: 'Cast Certificate',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:45:35.643249Z',
          },
          {
            id: 11,
            SubService: 5,
            document_type: 'VOTER_ID',
            DocumentName: 'Voter ID Card with full name',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:45:35.656098Z',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    ServiceName: 'Voter ID Card',
    Description: 'Voter ID Card',
    IsActive: true,
    CreatedAt: '2026-08-26T06:27:21.333895Z',
    UpdatedAt: '2026-08-26T06:27:21.333895Z',
    SubServices: [
      {
        id: 9,
        Service: 4,
        SubServiceName: 'New Voter ID Card',
        Description: null,
        IsActive: true,
        CreatedAt: '2026-08-26T06:37:39.010935Z',
        UpdatedAt: '2026-08-26T06:37:39.010935Z',
        RequiredDocuments: [
          {
            id: 17,
            SubService: 9,
            document_type: 'AADHAR',
            DocumentName: 'Aadhar Card',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:52:05.916984Z',
          },
          {
            id: 18,
            SubService: 9,
            document_type: 'PHOTO',
            DocumentName: 'Photo',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:52:05.924290Z',
          },
        ],
      },
    ],
  },
  {
    id: 5,
    ServiceName: 'Ayushman Card',
    Description: 'Ayushman Card',
    IsActive: true,
    CreatedAt: '2026-08-26T06:28:02.374379Z',
    UpdatedAt: '2026-08-26T06:28:02.374379Z',
    SubServices: [
      {
        id: 11,
        Service: 5,
        SubServiceName: 'New Ayushman Card',
        Description: null,
        IsActive: true,
        CreatedAt: '2026-08-26T06:38:52.171140Z',
        UpdatedAt: '2026-08-26T06:38:52.171578Z',
        RequiredDocuments: [
          {
            id: 22,
            SubService: 11,
            document_type: 'AADHAR',
            DocumentName: 'Aadhar Card',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:53:26.463539Z',
          },
          {
            id: 24,
            SubService: 11,
            document_type: 'RATION_CARD',
            DocumentName: 'Ration Card',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:54:11.539783Z',
          },
        ],
      },
    ],
  },
  {
    id: 8,
    ServiceName: 'PAN Card',
    Description: 'PAN Card',
    IsActive: true,
    CreatedAt: '2026-08-26T06:40:02.666819Z',
    UpdatedAt: '2026-08-26T06:40:02.666819Z',
    SubServices: [
      {
        id: 14,
        Service: 8,
        SubServiceName: 'New PAN Card',
        Description: null,
        IsActive: true,
        CreatedAt: '2026-08-26T06:40:40.339277Z',
        UpdatedAt: '2026-08-26T06:40:40.339277Z',
        RequiredDocuments: [
          {
            id: 30,
            SubService: 14,
            document_type: 'AADHAR',
            DocumentName: 'Aadhar Card - mobile linked',
            IsRequired: true,
            CreatedAt: '2026-08-26T06:57:55.261899Z',
          },
        ],
      },
    ],
  },
  ...INITIAL_45_SERVICES,
];

export const MOCK_SERVICE_VISITS: ServiceVisit[] = [
  {
    id: 6,
    visit_no: 'VIS-000003',
    customer: 3,
    customer_family_id: 'HTF-000002',
    customer_name: 'Dineshbhai Changani',
    customer_mobile: '8000231125',
    family_member: 3,
    family_member_name: 'Mitali Changani',
    service: 3,
    service_name: 'Aadhar Card',
    sub_service: 3,
    sub_service_name: 'New Aadhaar Card',
    checked_by: 1,
    checked_by_name: 'MITALI CHANGANI',
    status: 'PENDING',
    visit_date: '2026-08-27',
    remarks: 'Customer came for Adhar card',
    total_documents: 2,
    available_documents: 1,
    documents: [
      {
        id: 11,
        document_type: 'BIRTH_CERTIFICATE',
        document_name: 'Child Birth Certificate with new QR and with full name',
        status: 'NOT_AVAILABLE',
        document_file: null,
        created_at: '2026-08-27T06:13:04.057112Z',
        updated_at: '2026-08-27T06:13:04.057112Z',
      },
      {
        id: 12,
        document_type: 'AADHAR',
        document_name: 'Mother/Father Aadhaar Card',
        status: 'AVAILABLE',
        document_file: null,
        created_at: '2026-08-27T06:13:04.058114Z',
        updated_at: '2026-08-27T06:13:04.058114Z',
      },
    ],
    created_at: '2026-08-27T06:13:04.049533Z',
    updated_at: '2026-08-27T06:13:04.049533Z',
  },
  {
    id: 5,
    visit_no: 'VIS-000002',
    customer: 3,
    customer_family_id: 'HTF-000002',
    customer_name: 'Dineshbhai Changani',
    customer_mobile: '8000231125',
    family_member: null,
    family_member_name: null,
    service: 3,
    service_name: 'Aadhar Card',
    sub_service: 3,
    sub_service_name: 'New Aadhaar Card',
    checked_by: 1,
    checked_by_name: 'MITALI CHANGANI',
    status: 'PENDING',
    visit_date: '2026-08-26',
    remarks: 'Customer came for Adhar card',
    total_documents: 2,
    available_documents: 1,
    documents: [
      {
        id: 9,
        document_type: 'BIRTH_CERTIFICATE',
        document_name: 'Child Birth Certificate',
        status: 'NOT_AVAILABLE',
        document_file: null,
        created_at: '2026-08-26T11:02:09.640828Z',
        updated_at: '2026-08-26T11:02:09.640828Z',
      },
      {
        id: 10,
        document_type: 'AADHAR',
        document_name: 'Mother/Father Aadhaar Card',
        status: 'AVAILABLE',
        document_file: null,
        created_at: '2026-08-26T11:02:09.640828Z',
        updated_at: '2026-08-26T11:02:09.640828Z',
      },
    ],
    created_at: '2026-08-26T11:02:09.640828Z',
    updated_at: '2026-08-26T11:02:09.640828Z',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 2,
    transaction_no: 'TXN-000002',
    transaction_date: '2026-08-26',
    customer: 3,
    service: 3,
    sub_service: 3,
    staff: 1,
    family_id: 'HTF-000002',
    customer_name: 'Dineshbhai Changani',
    service_name: 'Aadhar Card',
    sub_service_name: 'New Aadhaar Card',
    staff_name: 'MITALI CHANGANI',
    bill_amount: '200.00',
    points_earned: 20,
    points_redeemed: 0,
    wallet_credit: '0.00',
    wallet_used: '0.00',
    net_wallet_change: 0.0,
    payment_mode: 'CASH',
    remarks: 'Demo transaction',
    created_at: '2026-08-26T07:33:01.770210Z',
    updated_at: '2026-08-26T07:33:01.770210Z',
  },
  {
    id: 1,
    transaction_no: 'TXN-000001',
    transaction_date: '2026-08-26',
    customer: 1,
    service: 3,
    sub_service: 3,
    staff: 1,
    family_id: 'HTF-000001',
    customer_name: 'Vitthalbhai Changani',
    service_name: 'Aadhar Card',
    sub_service_name: 'New Aadhaar Card',
    staff_name: 'MITALI CHANGANI',
    bill_amount: '250.00',
    points_earned: 20,
    points_redeemed: 0,
    wallet_credit: '0.00',
    wallet_used: '0.00',
    net_wallet_change: 0.0,
    payment_mode: 'CASH',
    remarks: 'Demo transaction',
    created_at: '2026-08-26T07:29:42.515340Z',
    updated_at: '2026-08-26T07:37:44.145034Z',
  },
];

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: 1,
    reminder_no: 'RMD-000001',
    customer: 1,
    customer_family_id: 'HTF-000001',
    customer_name: 'Vitthalbhai Changani',
    customer_mobile: '6789012345',
    service: 3,
    service_name: 'Aadhar Card',
    reminder_type: 'SERVICE_READY',
    subject: 'Adhar Card Service Ready',
    due_date: '2026-08-30',
    reminder_date: '2026-08-29',
    priority: 'HIGH',
    message_template: 'તમારી સેવા તૈયાર છે. HY-TECHની મુલાકાત લો.',
    follow_up_status: 'IN_PROGRESS',
    notes: 'Customer called twice',
    last_contact_date: '2026-08-26',
    customer_response: 'Will visit tomorrow',
    next_follow_up: '2026-08-27',
    follow_up_count: 1,
    created_by: 1,
    created_by_name: 'MITALI CHANGANI',
    follow_ups: [
      {
        id: 1,
        reminder: 1,
        contact_date: '2026-08-26',
        customer_response: 'Will visit tomorrow',
        next_follow_up: '2026-08-27',
        notes: 'Customer agreed to visit',
        contacted_by: 1,
        contacted_by_name: 'Mitali Changani',
        created_at: '2026-08-26T10:46:24.656903Z',
      },
    ],
    created_at: '2026-08-26T10:31:14.890181Z',
    updated_at: '2026-08-26T10:46:24.666902Z',
  },
];

export const MOCK_PENDING_WORK: PendingWork[] = [
  {
    id: 1,
    pending_no: 'PWD-000001',
    service_visit: 4,
    customer: 1,
    customer_family_id: 'HTF-000001',
    customer_name: 'Vitthalbhai Changani',
    customer_mobile: '6789012345',
    service: 3,
    service_name: 'Aadhar Card',
    pending_since: '2026-07-18',
    expected_date: '2026-07-20',
    priority: 'HIGH',
    pending_reason: 'Application processing',
    documents_pending: 'None',
    assigned_staff: 1,
    assigned_staff_name: 'MITALI CHANGANI',
    next_action: 'Check status and update customer',
    work_status: 'IN_PROGRESS',
    follow_up_date: '2026-07-19',
    notes: 'Customer called twice',
    created_by: 1,
    created_by_name: 'Mitali Changani',
    created_at: '2026-08-26T11:19:15.148265Z',
    updated_at: '2026-08-26T11:23:16.846847Z',
  },
  {
    id: 2,
    pending_no: 'PWD-000002',
    service_visit: 6,
    customer: 3,
    customer_family_id: 'HTF-000002',
    customer_name: 'Dineshbhai Changani',
    customer_mobile: '8000231125',
    service: 3,
    service_name: 'Aadhar Card',
    pending_since: '2026-08-27',
    expected_date: '2026-08-31',
    priority: 'MEDIUM',
    pending_reason: 'Birth Certificate scan pending',
    documents_pending: 'Child Birth Certificate with QR',
    assigned_staff: 1,
    assigned_staff_name: 'MITALI CHANGANI',
    next_action: 'Collect physical certificate',
    work_status: 'PENDING',
    follow_up_date: '2026-08-29',
    notes: 'Informed father to bring original',
    created_by: 1,
    created_by_name: 'Mitali Changani',
    created_at: '2026-08-27T08:00:00.000000Z',
    updated_at: '2026-08-27T08:00:00.000000Z',
  },
];

export const MOCK_PENDING_SUMMARY: PendingWorkSummary = {
  total: 2,
  pending: 1,
  in_progress: 1,
  blocked: 0,
  completed: 0,
  high_priority: 1,
  overdue: 1,
};

export const MOCK_EMPLOYEES: EmployeeUser[] = [
  {
    id: 1,
    username: 'admin',
    full_name: 'Admin Manager (સંચાલક)',
    email: 'admin@hytech.com',
    role: 'ADMIN',
    mobile_number: '9876543210',
    designation: 'Center Head & System Administrator',
    department: 'Management & IT',
    shift_timing: '09:00 AM - 07:00 PM',
    joining_date: '2024-01-01',
    basic_salary: 35000,
    is_active: true,
    created_at: '2026-08-25T00:00:00.000000Z',
  },
  {
    id: 4,
    username: 'jadav_durgesh',
    full_name: 'જાદવ દુર્ગેશ (Jadav Durgesh)',
    email: 'jadav.durgesh@hytech.com',
    role: 'STAFF',
    mobile_number: '9825123450',
    designation: 'Senior Aadhaar & Revenue Portal Operator',
    department: 'Front-Desk Operations',
    shift_timing: '09:30 AM - 06:30 PM',
    joining_date: '2024-03-15',
    basic_salary: 22000,
    is_active: true,
    created_at: '2026-08-01T09:00:00.000Z',
  },
  {
    id: 5,
    username: 'hardik_patel',
    full_name: 'હાર્દિકભાઈ (Hardikbhai)',
    email: 'hardik.patel@hytech.com',
    role: 'STAFF',
    mobile_number: '9879011223',
    designation: 'Digital Gujarat & Scholarship Specialist',
    department: 'Scheme & Welfare Desk',
    shift_timing: '09:30 AM - 06:30 PM',
    joining_date: '2024-06-01',
    basic_salary: 20000,
    is_active: true,
    created_at: '2026-08-05T09:00:00.000Z',
  },
  {
    id: 6,
    username: 'vinesh_sharma',
    full_name: 'વિનેશ (Vinesh)',
    email: 'vinesh@hytech.com',
    role: 'STAFF',
    mobile_number: '9904556677',
    designation: 'PAN Card, Passport & Voter ID Executive',
    department: 'Identity Card Services',
    shift_timing: '09:30 AM - 06:30 PM',
    joining_date: '2024-08-10',
    basic_salary: 19000,
    is_active: true,
    created_at: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 7,
    username: 'ravi_makwana',
    full_name: 'રવિ (Ravi)',
    email: 'ravi.makwana@hytech.com',
    role: 'STAFF',
    mobile_number: '9723445566',
    designation: 'Farmer Schemes & e-KYC Officer',
    department: 'Agriculture & PM Kisan',
    shift_timing: '10:00 AM - 07:00 PM',
    joining_date: '2024-11-01',
    basic_salary: 18500,
    is_active: true,
    created_at: '2026-08-12T09:00:00.000Z',
  },
  {
    id: 8,
    username: 'abdul_kadir',
    full_name: 'અબ્દુલ (Abdul)',
    email: 'abdul.kadir@hytech.com',
    role: 'STAFF',
    mobile_number: '9898778899',
    designation: 'Document Scanning & Biometric Verification Desk',
    department: 'Verification & Scanning',
    shift_timing: '09:30 AM - 06:30 PM',
    joining_date: '2025-01-15',
    basic_salary: 18000,
    is_active: true,
    created_at: '2026-08-15T09:00:00.000Z',
  },
  {
    id: 3,
    username: 'Mitali Changani',
    full_name: 'MITALI CHANGANI (મિતાલી ચાંગાણી)',
    email: '2302030400016@silveroakuni.ac.in',
    mobile_number: '06354456881',
    role: 'STAFF',
    designation: 'Customer Relationship & Intake Officer',
    department: 'Citizen Helpdesk',
    shift_timing: '09:30 AM - 06:30 PM',
    joining_date: '2025-02-01',
    basic_salary: 17500,
    is_active: true,
    created_at: '2026-08-26T07:29:20.494126Z',
  },
  {
    id: 2,
    username: 'staff01',
    full_name: 'Staff One (સહાયક સ્ટાફ)',
    email: 'staff1@hytech.com',
    role: 'STAFF',
    mobile_number: '9876543210',
    designation: 'Junior Data Entry Operator',
    department: 'General Operations',
    shift_timing: '09:30 AM - 06:30 PM',
    joining_date: '2025-03-01',
    basic_salary: 16000,
    is_active: true,
    created_at: '2026-08-26T12:28:59.600758Z',
  },
];

export const MOCK_HOLIDAYS: HolidayItem[] = [
  { id: 1, title: 'Makar Sankranti / Uttarayan', title_gu: 'મકરસંક્રાંતિ / ઉત્તરાયણ', date: '2026-01-14', day: 'Wednesday', type: 'GOVERNMENT', description: 'State public holiday for kite festival' },
  { id: 2, title: 'Vasi Uttarayan', title_gu: 'વાસી ઉત્તરાયણ', date: '2026-01-15', day: 'Thursday', type: 'REGIONAL', description: 'Center regional holiday' },
  { id: 3, title: 'Republic Day', title_gu: 'પ્રજાસત્તાક દિન', date: '2026-01-26', day: 'Monday', type: 'NATIONAL', description: 'National flag hoisting ceremony' },
  { id: 4, title: 'Maha Shivratri', title_gu: 'મહા શિવરાત્રી', date: '2026-02-15', day: 'Sunday', type: 'GOVERNMENT', description: 'Religious observance holiday' },
  { id: 5, title: 'Holi / Dhuleti', title_gu: 'હોળી - ધૂળેટી રંગોત્સવ', date: '2026-03-04', day: 'Wednesday', type: 'GOVERNMENT', description: 'Festival of colors holiday' },
  { id: 6, title: 'Cheti Chand / Gudi Padwa', title_gu: 'ચેટીચંડ / ગુડી પડવો', date: '2026-03-20', day: 'Friday', type: 'GOVERNMENT', description: 'Regional celebration' },
  { id: 7, title: 'Ram Navami', title_gu: 'રામ નવમી', date: '2026-03-28', day: 'Saturday', type: 'GOVERNMENT', description: 'Gazetted holiday' },
  { id: 8, title: 'Eid-ul-Fitr (Ramzan Eid)', title_gu: 'રમઝાન ઈદ (ઈદ-ઉલ-ફિત્ર)', date: '2026-03-21', day: 'Saturday', type: 'GOVERNMENT', description: 'Islamic calendar holiday' },
  { id: 9, title: 'Dr. B.R. Ambedkar Jayanti', title_gu: 'ડો. બાબાસાહેબ આંબેડકર જયંતિ', date: '2026-04-14', day: 'Tuesday', type: 'NATIONAL', description: 'Constitution father commemoration' },
  { id: 10, title: 'Gujarat Day', title_gu: 'ગુજરાત સ્થાપના દિન', date: '2026-05-01', day: 'Friday', type: 'REGIONAL', description: 'Gujarat State foundation day' },
  { id: 11, title: 'Bakri Eid (Eid-ul-Adha)', title_gu: 'બકરી ઈદ', date: '2026-05-28', day: 'Thursday', type: 'GOVERNMENT', description: 'Public holiday' },
  { id: 12, title: 'Independence Day', title_gu: 'સ્વાતંત્ર્ય દિન (૧૫મી ઓગસ્ટ)', date: '2026-08-15', day: 'Saturday', type: 'NATIONAL', description: '79th Independence day commemoration' },
  { id: 13, title: 'Raksha Bandhan', title_gu: 'રક્ષાબંધન (બળેવ)', date: '2026-08-28', day: 'Friday', type: 'GOVERNMENT', description: 'Festival of brother and sister' },
  { id: 14, title: 'Janmashtami', title_gu: 'શ્રીકૃષ્ણ જન્માષ્ટમી', date: '2026-09-04', day: 'Friday', type: 'GOVERNMENT', description: 'Lord Krishna birthday celebration' },
  { id: 15, title: 'Mahatma Gandhi Jayanti', title_gu: 'ગાંધી જયંતી', date: '2026-10-02', day: 'Friday', type: 'NATIONAL', description: 'National dry & public holiday' },
  { id: 16, title: 'Dussehra (Vijaya Dashami)', title_gu: 'વિજયાદશમી (દશેરા)', date: '2026-10-20', day: 'Tuesday', type: 'GOVERNMENT', description: 'Shastra pooja and festival' },
  { id: 17, title: 'Diwali (Deepawali)', title_gu: 'દિવાળી (દીપાવલી)', date: '2026-11-08', day: 'Sunday', type: 'GOVERNMENT', description: 'Grand festival of lights' },
  { id: 18, title: 'Bestu Varas (New Year)', title_gu: 'બેસતું વર્ષ (નવું વર્ષ)', date: '2026-11-09', day: 'Monday', type: 'GOVERNMENT', description: 'Gujarati new year start' },
  { id: 19, title: 'Bhai Dooj', title_gu: 'ભાઈબીજ', date: '2026-11-10', day: 'Tuesday', type: 'GOVERNMENT', description: 'Bhai Dooj festival holiday' },
];

export const MOCK_LEAVE_BALANCES: Record<number, LeaveBalance> = {
  4: { casual_total: 12, casual_used: 3, sick_total: 7, sick_used: 1, paid_total: 5, paid_used: 2 },
  5: { casual_total: 12, casual_used: 4, sick_total: 7, sick_used: 2, paid_total: 5, paid_used: 1 },
  6: { casual_total: 12, casual_used: 2, sick_total: 7, sick_used: 0, paid_total: 5, paid_used: 1 },
  7: { casual_total: 12, casual_used: 5, sick_total: 7, sick_used: 3, paid_total: 5, paid_used: 0 },
  8: { casual_total: 12, casual_used: 1, sick_total: 7, sick_used: 1, paid_total: 5, paid_used: 0 },
  1: { casual_total: 15, casual_used: 2, sick_total: 10, sick_used: 0, paid_total: 10, paid_used: 1 },
  2: { casual_total: 12, casual_used: 4, sick_total: 7, sick_used: 2, paid_total: 5, paid_used: 1 },
  3: { casual_total: 12, casual_used: 2, sick_total: 7, sick_used: 1, paid_total: 5, paid_used: 1 },
};

export const MOCK_LEAVES: LeaveRecord[] = [
  {
    id: 1,
    employee_id: 4,
    leave_type: 'CASUAL',
    start_date: '2026-08-18',
    end_date: '2026-08-19',
    days_count: 2,
    reason: 'Family social event & personal visit to hometown',
    status: 'APPROVED',
    applied_at: '2026-08-16',
    approved_by: 'Admin Manager',
  },
  {
    id: 2,
    employee_id: 4,
    leave_type: 'SICK',
    start_date: '2026-08-25',
    end_date: '2026-08-25',
    days_count: 1,
    reason: 'Seasonal fever and doctor rest advice',
    status: 'APPROVED',
    applied_at: '2026-08-25',
    approved_by: 'Admin Manager',
  },
  {
    id: 3,
    employee_id: 4,
    leave_type: 'CASUAL',
    start_date: '2026-09-15',
    end_date: '2026-09-16',
    days_count: 2,
    reason: 'Village religious function (માતાજીનો હવન)',
    status: 'PENDING',
    applied_at: '2026-09-06',
  },
  {
    id: 4,
    employee_id: 5,
    leave_type: 'PAID',
    start_date: '2026-08-10',
    end_date: '2026-08-11',
    days_count: 2,
    reason: 'Sister marriage ceremony preparations',
    status: 'APPROVED',
    applied_at: '2026-08-05',
    approved_by: 'Admin Manager',
  },
  {
    id: 5,
    employee_id: 6,
    leave_type: 'CASUAL',
    start_date: '2026-08-22',
    end_date: '2026-08-22',
    days_count: 1,
    reason: 'Urgent family bank & documentation work',
    status: 'APPROVED',
    applied_at: '2026-08-20',
    approved_by: 'Admin Manager',
  },
];

export const MOCK_ATTENDANCES: AttendanceRecord[] = [
  // Jadav Durgesh (id: 4) - September 2026
  { id: 401, employee_id: 4, date: '2026-09-01', day_name: 'Tuesday', in_time: '09:25 AM', out_time: '06:35 PM', status: 'PRESENT', work_hours: 9.1, notes: 'On-time punch' },
  { id: 402, employee_id: 4, date: '2026-09-02', day_name: 'Wednesday', in_time: '09:28 AM', out_time: '06:40 PM', status: 'PRESENT', work_hours: 9.2, notes: 'On-time punch' },
  { id: 403, employee_id: 4, date: '2026-09-03', day_name: 'Thursday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 404, employee_id: 4, date: '2026-09-04', day_name: 'Friday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Janmashtami Holiday' },
  { id: 405, employee_id: 4, date: '2026-09-05', day_name: 'Saturday', in_time: '09:40 AM', out_time: '02:30 PM', status: 'HALF_DAY', work_hours: 4.8, notes: 'Half day afternoon leave' },
  { id: 406, employee_id: 4, date: '2026-09-06', day_name: 'Sunday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Weekly off' },
  { id: 407, employee_id: 4, date: '2026-09-07', day_name: 'Monday', in_time: '09:22 AM', out_time: '06:35 PM', status: 'PRESENT', work_hours: 9.2, notes: 'Today logged in' },

  // Jadav Durgesh - August 2026 records sample
  { id: 408, employee_id: 4, date: '2026-08-28', day_name: 'Friday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Raksha Bandhan' },
  { id: 409, employee_id: 4, date: '2026-08-29', day_name: 'Saturday', in_time: '09:25 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 410, employee_id: 4, date: '2026-08-31', day_name: 'Monday', in_time: '09:20 AM', out_time: '06:45 PM', status: 'PRESENT', work_hours: 9.4, notes: 'Overtime 15 mins' },

  // Hardikbhai (id: 5)
  { id: 501, employee_id: 5, date: '2026-09-01', day_name: 'Tuesday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 502, employee_id: 5, date: '2026-09-02', day_name: 'Wednesday', in_time: '09:32 AM', out_time: '06:35 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 503, employee_id: 5, date: '2026-09-03', day_name: 'Thursday', in_time: '09:45 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 8.75, notes: 'Late by 15 mins' },
  { id: 504, employee_id: 5, date: '2026-09-04', day_name: 'Friday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Janmashtami' },
  { id: 505, employee_id: 5, date: '2026-09-05', day_name: 'Saturday', in_time: '09:28 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 506, employee_id: 5, date: '2026-09-06', day_name: 'Sunday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Weekly off' },
  { id: 507, employee_id: 5, date: '2026-09-07', day_name: 'Monday', in_time: '09:25 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Today logged in' },

  // Vinesh (id: 6)
  { id: 601, employee_id: 6, date: '2026-09-01', day_name: 'Tuesday', in_time: '09:20 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.1, notes: 'Normal shift' },
  { id: 602, employee_id: 6, date: '2026-09-02', day_name: 'Wednesday', in_time: '09:25 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 603, employee_id: 6, date: '2026-09-03', day_name: 'Thursday', in_time: undefined, out_time: undefined, status: 'ABSENT', work_hours: 0, notes: 'Uninformed absence' },
  { id: 604, employee_id: 6, date: '2026-09-04', day_name: 'Friday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Janmashtami' },
  { id: 605, employee_id: 6, date: '2026-09-05', day_name: 'Saturday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 606, employee_id: 6, date: '2026-09-06', day_name: 'Sunday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Weekly off' },
  { id: 607, employee_id: 6, date: '2026-09-07', day_name: 'Monday', in_time: '09:28 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Today logged in' },

  // Ravi (id: 7)
  { id: 701, employee_id: 7, date: '2026-09-01', day_name: 'Tuesday', in_time: '10:00 AM', out_time: '07:00 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Field work & office' },
  { id: 702, employee_id: 7, date: '2026-09-02', day_name: 'Wednesday', in_time: '10:05 AM', out_time: '07:05 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 703, employee_id: 7, date: '2026-09-03', day_name: 'Thursday', in_time: '10:00 AM', out_time: '07:00 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 704, employee_id: 7, date: '2026-09-04', day_name: 'Friday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Janmashtami' },
  { id: 705, employee_id: 7, date: '2026-09-05', day_name: 'Saturday', in_time: '10:00 AM', out_time: '07:00 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Normal shift' },
  { id: 706, employee_id: 7, date: '2026-09-06', day_name: 'Sunday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Weekly off' },
  { id: 707, employee_id: 7, date: '2026-09-07', day_name: 'Monday', in_time: '09:55 AM', out_time: '07:00 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Today logged in' },

  // Abdul (id: 8)
  { id: 801, employee_id: 8, date: '2026-09-01', day_name: 'Tuesday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Scanning desk' },
  { id: 802, employee_id: 8, date: '2026-09-02', day_name: 'Wednesday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Scanning desk' },
  { id: 803, employee_id: 8, date: '2026-09-03', day_name: 'Thursday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Scanning desk' },
  { id: 804, employee_id: 8, date: '2026-09-04', day_name: 'Friday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Janmashtami' },
  { id: 805, employee_id: 8, date: '2026-09-05', day_name: 'Saturday', in_time: '09:30 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Scanning desk' },
  { id: 806, employee_id: 8, date: '2026-09-06', day_name: 'Sunday', in_time: undefined, out_time: undefined, status: 'HOLIDAY', work_hours: 0, notes: 'Weekly off' },
  { id: 807, employee_id: 8, date: '2026-09-07', day_name: 'Monday', in_time: '09:28 AM', out_time: '06:30 PM', status: 'PRESENT', work_hours: 9.0, notes: 'Today logged in' },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 1,
    application_no: 'HT-APP-2026-000001',
    customer: 3,
    customer_name: 'Dineshbhai Changani',
    customer_mobile: '8000231125',
    customer_family_id: 'HTF-000002',
    family_member: 3,
    family_member_name: 'Mitali Changani',
    service: 103,
    service_name: 'PM Kisan Samman Nidhi / e-KYC',
    service_name_gu: 'P.M. કિસાન યોજના / e-KYC',
    sub_service: 1031,
    sub_service_name: 'Farmer e-KYC (ઓનલાઈન KYC)',
    category: 'GOVT_FORMS',
    status: 'GOVERNMENT_PROCESSING',
    priority: 'HIGH',
    government_app_no: 'PMK-GUJ-2026-98124',
    government_portal_url: 'https://pmkisan.gov.in',
    govt_fee: 0,
    service_charge: 70,
    total_fee: 70,
    payment_status: 'PAID',
    payment_mode: 'CASH',
    receipt_no: 'RCP-2026-0001',
    assigned_staff: 3,
    assigned_staff_name: 'MITALI CHANGANI',
    created_by: 1,
    created_by_name: 'Admin Manager',
    expected_date: '2026-09-08',
    sla_days: 5,
    documents: [
      {
        id: 1,
        document_name: 'Aadhaar Card (Mobile Linked)',
        document_type: 'AADHAR',
        status: 'VERIFIED',
        file_url: '/media/customer_documents/sample.pdf',
        verified_at: '2026-09-01T10:15:00Z',
      },
      {
        id: 2,
        document_name: 'Land Record 7/12 & 8-A',
        document_type: 'OTHER',
        status: 'AVAILABLE',
        file_url: '/media/customer_documents/sample.pdf',
      },
    ],
    form_data: {
      farmer_id: 'GJ-AMR-2026-112',
      land_area_acres: '3.5',
      bank_account_verified: 'Yes',
    },
    timeline: [
      {
        id: 'ev-1',
        timestamp: '2026-09-01T10:15:00Z',
        actor_name: 'MITALI CHANGANI',
        actor_role: 'STAFF',
        action: 'Application Created',
        old_status: undefined,
        new_status: 'DRAFT',
        notes: 'Citizen arrived at desk for PM Kisan renewal',
      },
      {
        id: 'ev-2',
        timestamp: '2026-09-01T10:18:00Z',
        actor_name: 'MITALI CHANGANI',
        actor_role: 'STAFF',
        action: 'Documents Verified',
        old_status: 'DRAFT',
        new_status: 'READY_TO_SUBMIT',
        notes: 'Aadhaar OTP and biometric matched with UIDAI server',
      },
      {
        id: 'ev-3',
        timestamp: '2026-09-01T10:25:00Z',
        actor_name: 'MITALI CHANGANI',
        actor_role: 'STAFF',
        action: 'Submitted to PM Kisan Portal',
        old_status: 'READY_TO_SUBMIT',
        new_status: 'GOVERNMENT_PROCESSING',
        notes: 'Portal Reference PMK-GUJ-2026-98124 generated',
      },
    ],
    notes: 'Citizen visited in-person with original token',
    created_at: '2026-09-01T10:15:00Z',
    updated_at: '2026-09-01T10:25:00Z',
  },
  {
    id: 2,
    application_no: 'HT-APP-2026-000002',
    customer: 1,
    customer_name: 'Vitthalbhai Changani',
    customer_mobile: '6789012345',
    customer_family_id: 'HTF-000001',
    family_member: 1,
    family_member_name: 'Vitthalbhai Changani',
    service: 113,
    service_name: 'Income Certificate',
    service_name_gu: 'આવકનો દાખલો',
    sub_service: 1131,
    sub_service_name: 'Income Certificate (3 Years Validity)',
    category: 'GOVT_FORMS',
    status: 'READY_TO_SUBMIT',
    priority: 'HIGH',
    government_app_no: 'INC-2026-778912',
    government_portal_url: 'https://digitalgujarat.gov.in',
    govt_fee: 20,
    service_charge: 80,
    total_fee: 100,
    payment_status: 'PAID',
    payment_mode: 'ONLINE/UPI',
    receipt_no: 'RCP-2026-0002',
    assigned_staff: 1,
    assigned_staff_name: 'Admin Manager',
    created_by: 1,
    created_by_name: 'Admin Manager',
    expected_date: '2026-09-07',
    sla_days: 5,
    documents: [
      {
        id: 3,
        document_name: 'Ration Card',
        document_type: 'RATION_CARD',
        status: 'VERIFIED',
        file_url: '/media/customer_documents/sample.pdf',
      },
      {
        id: 4,
        document_name: 'Aadhaar Card',
        document_type: 'AADHAR',
        status: 'VERIFIED',
        file_url: '/media/customer_documents/sample.pdf',
      },
      {
        id: 5,
        document_name: 'Electricity Bill / Talati Dakhalo',
        document_type: 'OTHER',
        status: 'AVAILABLE',
      },
    ],
    form_data: {
      annual_income_amount: '1,20,000',
      occupation: 'Agriculture / ખેતી',
      talati_recommendation: 'Approved',
    },
    timeline: [
      {
        id: 'ev-4',
        timestamp: '2026-09-02T11:00:00Z',
        actor_name: 'Admin Manager',
        actor_role: 'ADMIN',
        action: 'Application Created & Paid',
        old_status: 'DRAFT',
        new_status: 'READY_TO_SUBMIT',
        notes: 'Documents verified and revenue stamp fee collected',
      },
    ],
    notes: 'Urgent for student post-matric scholarship',
    created_at: '2026-09-02T11:00:00Z',
    updated_at: '2026-09-02T11:10:00Z',
  },
  {
    id: 3,
    application_no: 'HT-APP-2026-000003',
    customer: 3,
    customer_name: 'Dineshbhai Changani',
    customer_mobile: '8000231125',
    customer_family_id: 'HTF-000002',
    family_member: 4,
    family_member_name: 'Rekhaben Changani',
    service: 204,
    service_name: 'Ayushman Card (PMJAY) Update',
    service_name_gu: 'આયુષ્માન કાર્ડ',
    sub_service: 2041,
    sub_service_name: 'Ayushman e-KYC & PVC Print',
    category: 'CARD_SERVICES',
    status: 'COMPLETED',
    priority: 'HIGH',
    government_app_no: 'PMJAY-GJ-0044192',
    government_portal_url: 'https://beneficiary.nha.gov.in',
    govt_fee: 0,
    service_charge: 50,
    total_fee: 50,
    payment_status: 'PAID',
    payment_mode: 'CASH',
    receipt_no: 'RCP-2026-0003',
    assigned_staff: 3,
    assigned_staff_name: 'MITALI CHANGANI',
    created_by: 3,
    created_by_name: 'MITALI CHANGANI',
    expected_date: '2026-09-04',
    sla_days: 2,
    documents: [
      {
        id: 6,
        document_name: 'Aadhaar Card',
        document_type: 'AADHAR',
        status: 'VERIFIED',
      },
      {
        id: 7,
        document_name: 'Ration Card',
        document_type: 'RATION_CARD',
        status: 'VERIFIED',
      },
    ],
    form_data: {
      kyc_mode: 'Iris / Fingerprint',
      card_delivered: 'PVC Card Issued',
    },
    timeline: [
      {
        id: 'ev-5',
        timestamp: '2026-09-02T14:30:00Z',
        actor_name: 'MITALI CHANGANI',
        actor_role: 'STAFF',
        action: 'Application Completed & PVC Card Handed Over',
        old_status: 'GOVERNMENT_PROCESSING',
        new_status: 'COMPLETED',
        notes: 'Citizen collected smart PVC card in-person',
      },
    ],
    notes: 'Delivered successfully with official envelope',
    created_at: '2026-09-02T14:00:00Z',
    updated_at: '2026-09-02T14:30:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    timestamp: '2026-09-05T10:00:00Z',
    user_name: 'Admin Manager',
    user_role: 'ADMIN',
    action: 'SERVICE_CATALOG_SYNC',
    entity_type: 'ServiceCatalog',
    entity_id: '45-SERVICES',
    details: 'Seeded and activated 45 official government services across 6 categories',
  },
  {
    id: 2,
    timestamp: '2026-09-05T10:15:00Z',
    user_name: 'MITALI CHANGANI',
    user_role: 'STAFF',
    action: 'APPLICATION_CREATED',
    entity_type: 'Application',
    entity_id: 'HT-APP-2026-000001',
    details: 'Created PM Kisan application for Dineshbhai Changani',
  },
  {
    id: 3,
    timestamp: '2026-09-05T10:25:00Z',
    user_name: 'MITALI CHANGANI',
    user_role: 'STAFF',
    action: 'PAYMENT_RECORDED',
    entity_type: 'Transaction',
    entity_id: 'RCP-2026-0001',
    details: 'Collected ₹70 via CASH for application HT-APP-2026-000001',
  },
];

export const MOCK_VILLAGES: Village[] = [
  {
    id: 1,
    code: 'VIL-001',
    name: 'Bota',
    name_gu: 'બોટા',
    taluka: 'Botad',
    district: 'Botad',
    total_families: 126,
    total_citizens: 548,
    total_documents: 1840,
    male_count: 275,
    female_count: 273,
    is_active: true,
  },
  {
    id: 2,
    code: 'VIL-002',
    name: 'Gunjar',
    name_gu: 'ગુંજાર',
    taluka: 'Jasdan',
    district: 'Rajkot',
    total_families: 84,
    total_citizens: 382,
    total_documents: 1120,
    male_count: 195,
    female_count: 187,
    is_active: true,
  },
  {
    id: 3,
    code: 'VIL-003',
    name: 'Varna',
    name_gu: 'વરણા',
    taluka: 'Jasdan',
    district: 'Rajkot',
    total_families: 96,
    total_citizens: 412,
    total_documents: 1340,
    male_count: 210,
    female_count: 202,
    is_active: true,
  },
  {
    id: 4,
    code: 'VIL-004',
    name: 'Gadhada',
    name_gu: 'ગઢડા',
    taluka: 'Gadhada',
    district: 'Botad',
    total_families: 142,
    total_citizens: 620,
    total_documents: 2150,
    male_count: 312,
    female_count: 308,
    is_active: true,
  },
  {
    id: 5,
    code: 'VIL-005',
    name: 'Ranpur',
    name_gu: 'રાણપુર',
    taluka: 'Ranpur',
    district: 'Botad',
    total_families: 110,
    total_citizens: 480,
    total_documents: 1620,
    male_count: 245,
    female_count: 235,
    is_active: true,
  },
  {
    id: 6,
    code: 'VIL-006',
    name: 'Bhavnagar',
    name_gu: 'ભાવનગર',
    taluka: 'Bhavnagar',
    district: 'Bhavnagar',
    total_families: 320,
    total_citizens: 1420,
    total_documents: 4890,
    male_count: 720,
    female_count: 700,
    is_active: true,
  },
];

const createSampleDocs = (
  customAadhar?: string,
  customPan?: string,
  customVoter?: string,
  rationVerified: boolean = false
): GovDocumentItem[] => [
  {
    id: 'doc-1',
    title: 'Aadhaar Card',
    title_gu: 'આધાર કાર્ડ',
    type: 'AADHAR',
    status: customAadhar ? 'VERIFIED' : 'MISSING',
    document_no: customAadhar || undefined,
    uploaded_date: customAadhar ? '14 Aug 2026' : undefined,
    file_url: customAadhar ? '/media/customer_documents/sample.pdf' : undefined,
    is_required: true,
  },
  {
    id: 'doc-2',
    title: 'PAN Card',
    title_gu: 'પાન કાર્ડ',
    type: 'PAN',
    status: customPan ? 'VERIFIED' : 'MISSING',
    document_no: customPan || undefined,
    uploaded_date: customPan ? '10 Jun 2026' : undefined,
    file_url: customPan ? '/media/customer_documents/sample.pdf' : undefined,
    is_required: true,
  },
  {
    id: 'doc-3',
    title: 'Voter ID (Election Card)',
    title_gu: 'ચૂંટણી ઓળખકાર્ડ',
    type: 'VOTER_ID',
    status: customVoter ? 'UPLOADED' : 'MISSING',
    document_no: customVoter || undefined,
    uploaded_date: customVoter ? '01 Sep 2026' : undefined,
    file_url: customVoter ? '/media/customer_documents/sample.pdf' : undefined,
    is_required: true,
  },
  {
    id: 'doc-4',
    title: 'Ration Card',
    title_gu: 'રેશન કાર્ડ',
    type: 'RATION_CARD',
    status: rationVerified ? 'VERIFIED' : 'MISSING',
    document_no: rationVerified ? '0845129034' : undefined,
    uploaded_date: rationVerified ? '20 Jul 2026' : undefined,
    is_required: true,
  },
  {
    id: 'doc-5',
    title: 'Birth Certificate',
    title_gu: 'જન્મનો દાખલો',
    type: 'BIRTH_CERTIFICATE',
    status: 'MISSING',
    is_required: false,
  },
  {
    id: 'doc-6',
    title: 'Driving Licence',
    title_gu: 'ડ્રાઇવિંગ લાયસન્સ',
    type: 'DRIVING_LICENSE',
    status: 'MISSING',
    is_required: false,
  },
  {
    id: 'doc-7',
    title: 'Passport',
    title_gu: 'પાસપોર્ટ',
    type: 'OTHER',
    status: 'MISSING',
    is_required: false,
  },
  {
    id: 'doc-8',
    title: 'Ayushman Bharat Card',
    title_gu: 'આયુષ્માન ભારત કાર્ડ',
    type: 'OTHER',
    status: rationVerified ? 'VERIFIED' : 'MISSING',
    document_no: rationVerified ? 'PMJAY-GJ-092837' : undefined,
    is_required: false,
  },
];

export const MOCK_FAMILY_TREES: Record<string, { head: FamilyTreeNodeData; spouse?: FamilyTreeNodeData; children: FamilyTreeNodeData[] }> = {
  'HTF-000002': {
    head: {
      id: 301,
      family_id: 'HTF-000002',
      name: 'Dineshbhai Changani',
      relationship: 'HEAD',
      relationship_display: 'Head of Family',
      gender: 'MALE',
      age: 52,
      birth_date: '1974-04-12',
      mobile_number: '8000231125',
      is_head: true,
      is_active: true,
      generation: 2,
      documents_verified: 5,
      documents_total: 8,
      documents: createSampleDocs('XXXX XXXX 1125', 'BCDFG5678H', 'GJ/08/042/987654', true),
    },
    spouse: {
      id: 302,
      family_id: 'HTF-000002',
      name: 'Rekhaben Changani',
      relationship: 'WIFE',
      relationship_display: 'Wife',
      gender: 'FEMALE',
      age: 48,
      birth_date: '1978-08-20',
      mobile_number: '8000231125',
      is_head: false,
      is_active: true,
      generation: 2,
      spouse_id: 301,
      documents_verified: 4,
      documents_total: 8,
      documents: createSampleDocs('XXXX XXXX 8832', 'CWPKP9982M', 'GJ/08/042/987655', true),
    },
    children: [
      {
        id: 303,
        family_id: 'HTF-000002',
        name: 'Durgesh Changani',
        relationship: 'SON',
        relationship_display: 'Son',
        gender: 'MALE',
        age: 27,
        birth_date: '1999-05-14',
        mobile_number: '9876543210',
        is_head: false,
        is_active: true,
        generation: 3,
        parent_id: 301,
        documents_verified: 3,
        documents_total: 8,
        documents: createSampleDocs('XXXX XXXX 4821', 'ABCDE1234F', 'GJ/08/042/123456', false),
      },
      {
        id: 304,
        family_id: 'HTF-000002',
        name: 'Ravi Changani',
        relationship: 'SON',
        relationship_display: 'Son',
        gender: 'MALE',
        age: 24,
        birth_date: '2002-09-10',
        mobile_number: '9876543211',
        is_head: false,
        is_active: true,
        generation: 3,
        parent_id: 301,
        documents_verified: 2,
        documents_total: 8,
        documents: createSampleDocs('XXXX XXXX 7761', 'ZXCVB8899N', undefined, false),
      },
      {
        id: 305,
        family_id: 'HTF-000002',
        name: 'Manisha Changani',
        relationship: 'DAUGHTER',
        relationship_display: 'Daughter',
        gender: 'FEMALE',
        age: 21,
        birth_date: '2005-02-18',
        mobile_number: '9876543212',
        is_head: false,
        is_active: true,
        generation: 3,
        parent_id: 301,
        documents_verified: 2,
        documents_total: 8,
        documents: createSampleDocs('XXXX XXXX 9912', undefined, 'GJ/08/042/882190', false),
      },
      {
        id: 306,
        family_id: 'HTF-000002',
        name: 'Pooja Changani',
        relationship: 'DAUGHTER',
        relationship_display: 'Daughter',
        gender: 'FEMALE',
        age: 19,
        birth_date: '2007-11-25',
        mobile_number: '9876543213',
        is_head: false,
        is_active: true,
        generation: 3,
        parent_id: 301,
        documents_verified: 2,
        documents_total: 8,
        documents: createSampleDocs('XXXX XXXX 3341', undefined, undefined, false),
      },
    ],
  },
  'HTF-000001': {
    head: {
      id: 101,
      family_id: 'HTF-000001',
      name: 'Vitthalbhai Changani',
      relationship: 'HEAD',
      relationship_display: 'Head of Family',
      gender: 'MALE',
      age: 58,
      birth_date: '1968-05-23',
      mobile_number: '6789012345',
      is_head: true,
      is_active: true,
      generation: 2,
      documents_verified: 4,
      documents_total: 8,
      documents: createSampleDocs('XXXX XXXX 9012', 'LKJHG1234K', 'GJ/08/042/332145', true),
    },
    spouse: {
      id: 102,
      family_id: 'HTF-000001',
      name: 'Shantaben Changani',
      relationship: 'WIFE',
      relationship_display: 'Wife',
      gender: 'FEMALE',
      age: 54,
      birth_date: '1972-02-14',
      mobile_number: '6789012345',
      is_head: false,
      is_active: true,
      generation: 2,
      spouse_id: 101,
      documents_verified: 3,
      documents_total: 8,
      documents: createSampleDocs('XXXX XXXX 5543', undefined, 'GJ/08/042/332146', true),
    },
    children: [
      {
        id: 103,
        family_id: 'HTF-000001',
        name: 'Hargovindbhai Changani',
        relationship: 'SON',
        relationship_display: 'Son',
        gender: 'MALE',
        age: 32,
        birth_date: '1994-01-10',
        mobile_number: '9825123456',
        is_head: false,
        is_active: true,
        generation: 3,
        parent_id: 101,
        documents_verified: 3,
        documents_total: 8,
        documents: createSampleDocs('XXXX XXXX 8711', 'POIUY7766T', 'GJ/08/042/990011', false),
      },
      {
        id: 104,
        family_id: 'HTF-000001',
        name: 'Bhavnaben Changani',
        relationship: 'DAUGHTER',
        relationship_display: 'Daughter',
        gender: 'FEMALE',
        age: 29,
        birth_date: '1997-07-22',
        mobile_number: '9825123457',
        is_head: false,
        is_active: true,
        generation: 3,
        parent_id: 101,
        documents_verified: 2,
        documents_total: 8,
        documents: createSampleDocs('XXXX XXXX 4452', undefined, undefined, false),
      },
    ],
  },
};


